### ISSUE TITLE
multiple account support

### ISSUE THREAD

**Issue by george-lhj** [psschwei/github-activity#3]
As a user, I might have an enterprise account as well as a personal account that I have use during the week. Is it possible to support multiple accounts and retrieve/combine both so the final report generates the complete summary regardless of which account was used?

**Comment by psschwei** [comment]
In theory, this could be adapted to support passing multiple accounts. If someone wants to submit a PR for it, I'd take a look. 

Ideally, it would use some kind of config file to specify the account details, perhaps something like

```toml
[[accounts]]
name = "github"
domain = "github.com"
token = "xxx"

[[accounts]]
name = "github enterprise"
domain = "github.enterprise.com"
token = "yyy"
```
